/**
 * 🎯 CRITERIA GENERATION HOOK
 *
 * Purpose: Manages AI-powered criteria generation for vendor evaluation.
 * Extracts business logic from CriteriaBuilder component.
 *
 * Features:
 * - AI-powered criteria generation based on category and requirements
 * - Fallback to standard criteria when AI fails
 * - Loading state management
 * - Error handling with user-friendly fallbacks
 *
 * @module hooks/useCriteriaGeneration
 */

import { useState } from 'react';

/**
 * Criteria structure for component use
 */
export interface Criteria {
  id: string;
  name: string;
  explanation: string;
  importance: 'low' | 'medium' | 'high';
  type: string;
}

/**
 * Tech request data for criteria generation
 */
export interface TechRequest {
  category: string;
  requirements?: string[];
  description?: string;
}

/**
 * Chat message structure
 */
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
}

/**
 * Hook return type
 */
export interface UseCriteriaGenerationReturn {
  isGenerating: boolean;
  generateInitialCriteria: (request: TechRequest) => Promise<{
    criteria: Criteria[];
    message: ChatMessage;
  }>;
  generateFallbackCriteria: (request: TechRequest) => Criteria[];
}

/**
 * Generate fallback criteria when AI fails
 *
 * Purpose: Provides standard evaluation criteria as a fallback.
 * Now returns empty array - n8n handles all criteria generation.
 *
 * @param request - Tech request data
 * @returns Empty array - criteria should come from n8n
 */
const createFallbackCriteria = (request: TechRequest): Criteria[] => {
  // n8n handles all criteria generation - no local fallback needed
  return [];
};

/**
 * Custom hook for AI-powered criteria generation
 *
 * Purpose: Manages criteria generation with AI service integration.
 * Handles loading states, errors, and fallback generation.
 *
 * @returns Object with generation state and functions
 *
 * @example
 * ```typescript
 * const { isGenerating, generateInitialCriteria, generateFallbackCriteria } = useCriteriaGeneration();
 *
 * // Generate criteria with AI
 * const { criteria, message } = await generateInitialCriteria({
 *   category: 'CRM Software',
 *   requirements: ['mobile app', 'integrations']
 * });
 *
 * // Or use fallback
 * const fallbackCriteria = generateFallbackCriteria(techRequest);
 * ```
 *
 * @remarks
 * - Automatically handles AI failures with fallback
 * - Returns both criteria and explanatory chat message
 * - Loading state can be used to show spinners
 */
export const useCriteriaGeneration = (): UseCriteriaGenerationReturn => {
  const [isGenerating, setIsGenerating] = useState(false);

  /**
   * Generate initial criteria using AI service
   * Note: n8n now handles criteria generation during project creation
   * This returns empty criteria - the actual criteria come from n8n storage
   *
   * @param request - Tech request with category and requirements
   * @returns Promise with empty criteria (n8n provides actual criteria)
   */
  const generateInitialCriteria = async (
    request: TechRequest
  ): Promise<{ criteria: Criteria[]; message: ChatMessage }> => {
    setIsGenerating(true);

    try {
      // n8n handles all criteria generation during project creation
      // This hook is no longer the source of criteria
      const emptyMessage: ChatMessage = {
        id: `gen-${Date.now()}`,
        role: 'assistant',
        content: `Criteria are generated by n8n during project creation.`,
        timestamp: new Date()
      };

      return {
        criteria: [],
        message: emptyMessage
      };
    } finally {
      setIsGenerating(false);
    }
  };

  /**
   * Generate fallback criteria
   * Public accessor for fallback criteria generation
   *
   * @param request - Tech request data
   * @returns Array of fallback criteria
   */
  const generateFallbackCriteria = (request: TechRequest): Criteria[] => {
    return createFallbackCriteria(request);
  };

  return {
    isGenerating,
    generateInitialCriteria,
    generateFallbackCriteria
  };
};
