/**
 * n8n Integration Type Definitions
 *
 * This file contains all types for communicating with n8n workflows,
 * including request/response formats for AI-powered project creation.
 *
 * @module types/n8n
 */

/**
 * Request payload for n8n project creation webhook
 */
export interface N8nProjectCreationRequest {
  user_id: string;
  session_id: string;
  company_context: string;
  solution_requirements: string;
  timestamp: string; // ISO 8601 format
}

/**
 * Project data returned from n8n AI
 */
export interface N8nProject {
  name: string;
  description: string;
  category: string;
}

/**
 * Criterion generated by n8n AI
 * Note: n8n uses "description" which maps to our app's "explanation" field
 */
export interface N8nCriterion {
  id: string;
  name: string;
  description: string; // Maps to "explanation" in app
  importance: 'low' | 'medium' | 'high';
  type: 'feature' | 'technical' | 'business' | 'compliance';
  isArchived: boolean;
}

/**
 * Error object in n8n response
 */
export interface N8nError {
  code: 'INVALID_INPUT' | 'AI_PROCESSING_ERROR' | 'INTERNAL_ERROR';
  message: string;
}

/**
 * Response from n8n project creation webhook
 */
export interface N8nProjectCreationResponse {
  success: boolean;
  project?: N8nProject;
  criteria?: N8nCriterion[];
  error?: N8nError;
}

/**
 * Transformed project data ready for app use
 */
export interface TransformedProject {
  id: string;
  name: string;
  description: string;
  category: string;
  status: 'draft' | 'in-progress' | 'completed' | 'archived';
  created_at: string;
  updated_at: string;
  user_id: string;
  techRequest: {
    companyContext: string;
    solutionRequirements: string;
  };
}

/**
 * Transformed criterion data ready for app use
 */
export interface TransformedCriterion {
  id: string;
  name: string;
  explanation: string; // Mapped from n8n's "description"
  importance: 'low' | 'medium' | 'high';
  type: string;
  isArchived: boolean;
}

/**
 * Result of project creation operation
 */
export interface ProjectCreationResult {
  project: TransformedProject;
  criteria: TransformedCriterion[];
}

// ===========================================
// Email Collection Types (SP_017)
// ===========================================

/**
 * Device metadata for analytics
 */
export interface DeviceMetadata {
  browser: string;
  os: string;
  deviceType: 'mobile' | 'tablet' | 'desktop';
  screenResolution: string;
  timezone: string;
}

/**
 * Request payload for n8n email collection webhook
 */
export interface EmailCollectionRequest {
  email: string;
  user_id: string;
  timestamp: string; // ISO 8601 format
  device_metadata: DeviceMetadata;
}

/**
 * Response from n8n email collection webhook
 */
export interface EmailCollectionResponse {
  success: boolean;
  message?: string;
  error?: {
    code: string;
    message: string;
  };
}

/**
 * Email collection data stored in localStorage
 */
export interface EmailCollectionStorage {
  email_submitted: boolean;
  email: string;
  timestamp: string;
  email_passed_to_n8n: boolean;
}

// ===========================================
// Vendor Battlecards Types (SP_023)
// ===========================================

/**
 * Individual cell in a battlecard row
 */
export interface BattlecardCell {
  vendor_name: string;
  text: string; // 1-2 intro sentences + bullet list if 2+ items
  source_urls: string[]; // Array of ALL source URLs used during research
}

/**
 * Request payload for n8n battlecard row generation webhook
 */
export interface BattlecardRowRequest {
  user_id: string;
  session_id: string;
  project_id: string;
  project_context: string;
  vendor_names: string[];
  criteria: Array<{
    id: string;
    name: string;
    explanation: string;
    importance: 'low' | 'medium' | 'high';
    type: string;
  }>;
  already_filled_categories: string[];
  is_mandatory_category?: boolean;
  requested_category?: string;
  timestamp: string;
}

/**
 * Single battlecard row response from n8n
 */
export interface BattlecardRow {
  row_id: string;
  category_title: string;
  category_definition?: string;
  cells: BattlecardCell[];
  timestamp: string;
}

/**
 * Response from n8n battlecard row webhook
 */
export interface BattlecardRowResponse {
  success: boolean;
  row?: BattlecardRow;
  research_summary?: string;
  error?: {
    code: 'INVALID_INPUT' | 'AI_PROCESSING_ERROR' | 'TIMEOUT' | 'INTERNAL_ERROR';
    message: string;
  };
}
