/**
 * n8n Integration Type Definitions
 *
 * This file contains all types for communicating with n8n workflows,
 * including request/response formats for AI-powered project creation.
 *
 * @module types/n8n
 */

/**
 * Request payload for n8n project creation webhook
 */
export interface N8nProjectCreationRequest {
  user_id: string;
  session_id: string;
  company_context: string;
  solution_requirements: string;
  timestamp: string; // ISO 8601 format
}

/**
 * Project data returned from n8n AI
 */
export interface N8nProject {
  name: string;
  description: string;
  category: string;
}

/**
 * Criterion generated by n8n AI
 * Note: n8n uses "description" which maps to our app's "explanation" field
 */
export interface N8nCriterion {
  id: string;
  name: string;
  description: string; // Maps to "explanation" in app
  importance: 'low' | 'medium' | 'high';
  type: 'feature' | 'technical' | 'business' | 'compliance';
  isArchived: boolean;
}

/**
 * Error object in n8n response
 */
export interface N8nError {
  code: 'INVALID_INPUT' | 'AI_PROCESSING_ERROR' | 'INTERNAL_ERROR';
  message: string;
}

/**
 * Response from n8n project creation webhook
 */
export interface N8nProjectCreationResponse {
  success: boolean;
  project?: N8nProject;
  criteria?: N8nCriterion[];
  error?: N8nError;
}

/**
 * Transformed project data ready for app use
 */
export interface TransformedProject {
  id: string;
  name: string;
  description: string;
  category: string;
  status: 'draft' | 'in-progress' | 'completed' | 'archived';
  created_at: string;
  updated_at: string;
  user_id: string;
  techRequest: {
    companyContext: string;
    solutionRequirements: string;
  };
}

/**
 * Transformed criterion data ready for app use
 */
export interface TransformedCriterion {
  id: string;
  name: string;
  explanation: string; // Mapped from n8n's "description"
  importance: 'low' | 'medium' | 'high';
  type: string;
  isArchived: boolean;
}

/**
 * Result of project creation operation
 */
export interface ProjectCreationResult {
  project: TransformedProject;
  criteria: TransformedCriterion[];
}
